
name = "todo-list-api2"
main = "main.ts"
compatibility_date = "2025-02-11"

[durable_objects]

bindings = [
  { name = "TODO_DO", class_name = "TodoDO" },
]

[[migrations]]

tag = "v1"
new_classes = ["TodoDO"]
