
name = "todo-list-api2"
main = "main.ts"
compatibility_date = "2025-02-11"

[durable_objects]

bindings = [
  { name = "TODO_LIST", class_name = "TodoListDO" },
]

[[migrations]]

tag = "v1"
new_classes = ["TodoListDO"]
